# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: public.media.storage
        internal_loader:
            filesystem:
                locator: filesystem
                data_root:
                    # Default:
                    - '%kernel.project_dir%/public'

    data_loader: flysystem_loader
    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: public.media.storage
                root_url: "/uploads"
                cache_prefix: cache

    cache: flysystem_resolver
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: public/watermark.png
                    size: 0.5
                    position: bottomleft

